/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorShow: typeof import('./resources/js/components/AuthorShow.vue')['default']
    AuthorsList: typeof import('./resources/js/components/AuthorsList.vue')['default']
    BookShow: typeof import('./resources/js/components/BookShow.vue')['default']
    BooksList: typeof import('./resources/js/components/BooksList.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/admin/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/admin/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/admin/@core/components/cards/CardStatisticsWithImages.vue')['default']
    Login: typeof import('./resources/js/components/Login.vue')['default']
    MoreBtn: typeof import('./resources/js/admin/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/js/admin/@core/components/ThemeSwitcher.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
