/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorShow: typeof import('./resources/js/components/AuthorShow.vue')['default']
    AuthorsList: typeof import('./resources/js/components/AuthorsList.vue')['default']
    BookShow: typeof import('./resources/js/components/BookShow.vue')['default']
    BooksList: typeof import('./resources/js/components/BooksList.vue')['default']
    ExampleComponent: typeof import('./resources/js/components/ExampleComponent.vue')['default']
    Login: typeof import('./resources/js/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
